### ISSUE TITLE
Error: retrieving gpg key timed out.

### ISSUE THREAD

**Issue by drgeb** [tomgeorge/devbox#1]
Hi Tomgeorge,
I am trying to build your Docker Dev box but running into this issue:
http://ansible.com/
 More info: https://launchpad.net/~ansible/+archive/ubuntu/ansible
gpg: keyring `/tmp/tmp5xuldrpg/secring.gpg' created
gpg: keyring `/tmp/tmp5xuldrpg/pubring.gpg' created
gpg: requesting key 7BB9C367 from hkp server keyserver.ubuntu.com
Error: retrieving gpg key timed out.
gpg: /tmp/tmp5xuldrpg/trustdb.gpg: trustdb created
gpg: key 7BB9C367: public key "Launchpad PPA for Ansible, Inc." imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

Not sure you have any solution for this ?

**Comment by tomgeorge** [comment]
Hi,

Did you happen to see if the other `add-apt-repository` command above it successfully added the repository and got the key from the keyserver?

Could you paste the result of `make build > build.out` in this issue thread?

**Comment by tomgeorge** [comment]
My guess is that it's something related to [this issue](https://unix.stackexchange.com/questions/75892/keyserver-timed-out-when-trying-to-add-a-gpg-public-key).  I mean, there is a very slim chance that the keyserver was unavailable but I doubt it.

As a workaround, you could try adding 

```Dockerfile
RUN  gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7BB9C367
```

before the

```Dockerfile
RUN add-apt-repository ppa:neovim/unstable && \ ...
```

line

**Comment by tomgeorge** [comment]
hey @drgeb, have you been able to try any of the steps I suggested?
